# Generated by Django 4.1.3 on 2022-11-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("country_of_issue", models.CharField(max_length=20)),
                ("date_of_issue", models.DateTimeField()),
                ("date_of_expiration", models.DateTimeField()),
                ("authority_issuing_the_document", models.CharField(max_length=20)),
            ],
        ),
    ]
