# Generated by Django 4.1.3 on 2022-11-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0002_secondaryeducation_alter_document_date_of_expiration_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bachelorsdegree",
            name="student",
        ),
        migrations.RemoveField(
            model_name="doctorate",
            name="student",
        ),
        migrations.RemoveField(
            model_name="mastersdegree",
            name="student",
        ),
        migrations.AddField(
            model_name="bachelorsdegree",
            name="student_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.document",
                to_field="id_number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorate",
            name="student_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.document",
                to_field="id_number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mastersdegree",
            name="student_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.document",
                to_field="id_number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="bachelors_degree",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.bachelorsdegree",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="doctorate",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.doctorate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="masters_degree",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.mastersdegree",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="id_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="secondaryeducation",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.document",
                to_field="id_number",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="document_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.document",
                to_field="id_number",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="secondary_education",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.secondaryeducation",
            ),
        ),
    ]
