# Generated by Django 4.1.3 on 2022-12-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_remove_bachelorsdegree_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course_grade",
            field=models.CharField(default="BachelorsDegree", max_length=20),
        ),
    ]
