# Generated by Django 4.1.4 on 2022-12-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("codice_fiscale", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=1)),
                ("password", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=100)),
                ("region_of_birth", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "phone_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=15, unique=True)),
                ("type", models.CharField(max_length=15)),
                ("country_of_issue", models.CharField(max_length=30)),
                ("date_of_issue", models.DateField()),
                ("date_of_expiration", models.DateField()),
                ("authority_issuing_the_document", models.CharField(max_length=50)),
                (
                    "document_img",
                    models.ImageField(
                        blank=True, upload_to="templates/users/%Y/%m/%d/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentEnrolled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_selected",
                    models.CharField(default="BachelorsDegree", max_length=20),
                ),
                (
                    "document_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.document",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_of_degree", models.CharField(max_length=15)),
                ("university_nation", models.CharField(max_length=15)),
                ("year_of_enrollment", models.DateField()),
                ("year_of_graduation", models.DateField()),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.discipline",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.document",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
    ]
