# Generated by Django 4.1.3 on 2022-12-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(max_length=15)),
                ('country_of_issue', models.CharField(max_length=30)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiration', models.DateField()),
                ('authority_issuing_the_document', models.CharField(max_length=50)),
            ],
        ),
    ]
