# Generated by Django 4.1.3 on 2022-12-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
