# Generated by Django 4.1.3 on 2022-12-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_document_students_degree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='StudentEnrolled',
        ),
    ]
