# Generated by Django 4.1.4 on 2022-12-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
