# Generated by Django 4.1.4 on 2023-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_document_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(max_length=100),
        ),
    ]
