# Generated by Django 4.1.4 on 2023-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_document_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date_of_expiration",
            field=models.DateField(verbose_name="%Y"),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_of_issue",
            field=models.DateField(verbose_name="%Y"),
        ),
    ]
