# Generated by Django 4.1.4 on 2023-01-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_rename_student_id_degree_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="home.discipline",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
