# Generated by Django 4.1.4 on 2023-01-04 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_degree_discipline_alter_discipline_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentenrolled",
            name="document_id",
        ),
        migrations.AddField(
            model_name="studentenrolled",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="degree",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.discipline",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="degree",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="studentenrolled",
            name="course_selected",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.discipline",
                to_field="name",
            ),
        ),
    ]
