# Generated by Django 4.1.4 on 2023-01-04 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_studentenrolled_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrolled",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
